# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('usermail', models.EmailField(max_length=254)),
            ],
        ),
    ]
